demo: learn_mu_pair_stack_ident_stress
seed: 0
dt: 0.01
dtype: float32
device: cpu

task:
  kind: mu_stack_pair

  mu_ground_true: 0.6
  mu_pair_true: 0.2
  mu_ground_init: 0.1
  mu_pair_init: 0.1
  mu_max: 1.0
  lr: 0.25

  train_iters: 50
  rollout_steps: 5
  n_train: 4
  n_val: 4

  omega_range: [3.0, 8.0]
  vx_range: [0.0, 0.2]
  vx_bottom_range: [2.0, 3.0]
  val_omega_range: [1.0, 4.0]
  val_vx_range: [0.0, 0.2]
  val_vx_bottom_range: [2.0, 3.0]

  ood_cases:
    - name: dt_2x
      dt: 0.02
      steps: 5
      n: 4
      omega_range: [4.0, 10.0]
      vx_range: [0.0, 0.2]
      vx_bottom_range: [2.0, 3.0]
    - name: mass_2x
      dt: 0.01
      steps: 5
      n: 4
      omega_range: [4.0, 10.0]
      vx_range: [0.0, 0.2]
      vx_bottom_range: [2.0, 3.0]
      engine_overrides:
        mass: 2.0
    - name: dt_2x_mass_2x
      dt: 0.02
      steps: 5
      n: 4
      omega_range: [4.0, 10.0]
      vx_range: [0.0, 0.2]
      vx_bottom_range: [2.0, 3.0]
      engine_overrides:
        mass: 2.0

engine:
  mass: 1.0
  radius: 0.5
  gravity: 9.81
  ground_height: 0.0
  contact_slop: 0.001
  impact_velocity_min: 0.2
  pgs_iters: 20
  baumgarte_beta: 0.2
  residual_tol: 1.0e-6
  warm_start: true

loss:
  w_q: 0.1
  w_v: 1.0
  w_pen: 0.0
  w_comp: 0.0
  w_res: 0.0
