demo: bouncing_ball_1d
seed: 0
dt: 0.005
steps: 2000
dtype: float64

device: cuda

params:
  mass: 1.0
  gravity: 9.81
  restitution: 0.85
  ground_height: 0.0
  q_slop: 0.001
  v_sleep: 0.1
  q0: 1.0
  v0: 0.0

failsafe:
  penetration_hard: 0.2
  v_hard: 50.0
  energy_factor_hard: 100.0
